### ISSUE TITLE
Consertar nome do Projeto

### ISSUE THREAD

**Issue by eduardolfalcao** [Lucasdevs/P2-Unifacisa#1]
Oi Lucas
Você tem total liberdade para definir o nome do seu projeto, mas uma dica que gostaria de dar é que podemos organizar todo o conteúdo e programa que escrevermos nessa disciplina em um repositório (em vez de dividir em dois repositórios, sendo um para cada unidade).
Portanto, minha sugestão é que você renomeie o seu projeto.

Abç

**Comment by Lucasdevs** [comment]
Obrigado pela dica professor, abraço!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Eduardo Falcão<mailto:notifications@github.com>
Enviado:domingo, 23 de agosto de 2020 09:49
Para: Lucasdevs/P2-Unifacisa-PrimeiraUnidade<mailto:P2-Unifacisa-PrimeiraUnidade@noreply.github.com>
Cc:Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [Lucasdevs/P2-Unifacisa-PrimeiraUnidade] Consertar nome do Projeto (#1)


Oi Lucas
Você tem total liberdade para definir o nome do seu projeto, mas uma dica que gostaria de dar é que podemos organizar todo o conteúdo e programa que escrevermos nessa disciplina em um repositório (em vez de dividir em dois repositórios, sendo um para cada unidade).
Portanto, minha sugestão é que você renomeie o seu projeto.

Abç
